{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "aws-adot-amp.serviceAccountName" . }}
  namespace: {{ template "aws-adot-amp.namespace" . }}
  labels:
    {{- include "aws-adot-amp.labels" . | indent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
