# Default values for alertmanager-mixin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Provide a name to substitute for the full names of resources
fullnameOverride: ""

# -- Additional labels to add to the Prometheus rules
additionalLabels: {}

# -- Additional annotations to add to the Prometheus rules
additionalAnnotations: {}

grafana:
  # Grafana folder in which to store the dashboards
  folder: monitoring
