---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" (include "promtail-mixin.fullname" .) "rules" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "promtail-mixin.namespace" . }}
  annotations:
{{ include "promtail-mixin.annotations" . | indent 4 }}
{{- if .Values.additionalAnnotations }}
{{ toYaml .Values.additionalAnnotations | indent 4 }}
{{- end }}
  labels:
    app: {{ include "promtail-mixin.name" . }}
{{ include "promtail-mixin.labels" . | indent 4 }}
{{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | indent 4 }}
{{- end }}
spec:
  groups:
  - name: promtail_rules
    rules:
    - expr: histogram_quantile(0.99, sum(rate(promtail_request_duration_seconds_bucket[1m])) by (le, job))
      record: job:promtail_request_duration_seconds:99quantile
    - expr: histogram_quantile(0.50, sum(rate(promtail_request_duration_seconds_bucket[1m])) by (le, job))
      record: job:promtail_request_duration_seconds:50quantile
    - expr: sum(rate(promtail_request_duration_seconds_sum[1m])) by (job) / sum(rate(promtail_request_duration_seconds_count[1m])) by (job)
      record: job:promtail_request_duration_seconds:avg
    - expr: sum(rate(promtail_request_duration_seconds_bucket[1m])) by (le, job)
      record: job:promtail_request_duration_seconds_bucket:sum_rate
    - expr: sum(rate(promtail_request_duration_seconds_sum[1m])) by (job)
      record: job:promtail_request_duration_seconds_sum:sum_rate
    - expr: sum(rate(promtail_request_duration_seconds_count[1m])) by (job)
      record: job:promtail_request_duration_seconds_count:sum_rate
    - expr: histogram_quantile(0.99, sum(rate(promtail_request_duration_seconds_bucket[1m])) by (le, job, namespace))
      record: job_namespace:promtail_request_duration_seconds:99quantile
    - expr: histogram_quantile(0.50, sum(rate(promtail_request_duration_seconds_bucket[1m])) by (le, job, namespace))
      record: job_namespace:promtail_request_duration_seconds:50quantile
    - expr: sum(rate(promtail_request_duration_seconds_sum[1m])) by (job, namespace) / sum(rate(promtail_request_duration_seconds_count[1m])) by (job, namespace)
      record: job_namespace:promtail_request_duration_seconds:avg
    - expr: sum(rate(promtail_request_duration_seconds_bucket[1m])) by (le, job, namespace)
      record: job_namespace:promtail_request_duration_seconds_bucket:sum_rate
    - expr: sum(rate(promtail_request_duration_seconds_sum[1m])) by (job, namespace)
      record: job_namespace:promtail_request_duration_seconds_sum:sum_rate
    - expr: sum(rate(promtail_request_duration_seconds_count[1m])) by (job, namespace)
      record: job_namespace:promtail_request_duration_seconds_count:sum_rate
    - expr: histogram_quantile(0.99, sum(rate(promtail_request_duration_seconds_bucket[1m])) by (le, job, status_code, namespace))
      record: job_status_code_namespace:promtail_request_duration_seconds:99quantile
    - expr: histogram_quantile(0.50, sum(rate(promtail_request_duration_seconds_bucket[1m])) by (le, job, status_code, namespace))
      record: job_status_code_namespace:promtail_request_duration_seconds:50quantile
    - expr: sum(rate(promtail_request_duration_seconds_sum[1m])) by (job, status_code, namespace) / sum(rate(promtail_request_duration_seconds_count[1m])) by (job, status_code, namespace)
      record: job_status_code_namespace:promtail_request_duration_seconds:avg
    - expr: sum(rate(promtail_request_duration_seconds_bucket[1m])) by (le, job, status_code, namespace)
      record: job_status_code_namespace:promtail_request_duration_seconds_bucket:sum_rate
    - expr: sum(rate(promtail_request_duration_seconds_sum[1m])) by (job, status_code, namespace)
      record: job_status_code_namespace:promtail_request_duration_seconds_sum:sum_rate
    - expr: sum(rate(promtail_request_duration_seconds_count[1m])) by (job, status_code, namespace)
      record: job_status_code_namespace:promtail_request_duration_seconds_count:sum_rate
