# Copyright (C) 2020 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v2
name: coredns-mixin
description: A Helm chart for CoreDNS Mixin
home: https://charts.portefaix.xyz
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Prometheus_software_logo.svg/242px-Prometheus_software_logo.svg.png
sources:
  - https://github.com/nlamirault/portefaix-hub/tree/master/charts/coredns-mixin
type: application
keywords:
  - coredns
  - prometheus
  - monitoring-mixin
  - portefaix

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 1.0.0

maintainers:
  - name: nlamirault
    email: nicolas.lamirault@gmail.com

# https://artifacthub.io/docs/topics/repositories/
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: coredns
      url: https://coredns.io
    - name: Portefaix
      url: https://portefaix.xyz
    - name: Monitoring mixins
      url: https://github.com/nlamirault/monitoring-mixins
  artifacthub.io/maintainers: |
    - name: nlamirault
      email: nicolas.lamirault@gmail.com
  artifacthub.io/signKey: |
    fingerprint: C39918B3EBDE35C23B8D0B8E5F99269A6FCA437C
    url: https://keybase.io/nlamirault/pgp_keys.asc
  artifacthub.io/changes: |
    - kind: added
      description: Use monitoring-mixins v0.19.0
