# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: InternetGateway
metadata:
  {{- with .Values.additionalAnnotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    {{- include "ack-factory.labels" . | nindent 4 }}
  name: {{ include "ack-factory.name" . }}
  namespace: {{ template "ack-factory.namespace" . }}
spec:
  vpcRef:
    from:
      name: {{ include "ack-factory.name" . }}
  tags:
  {{- toYaml .Values.ack.tags | nindent 4 }}
---
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: NATGateway
metadata:
  {{- with .Values.additionalAnnotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    {{- include "ack-factory.labels" . | nindent 4 }}
  name: {{ include "ack-factory.name" . }}
  namespace: {{ template "ack-factory.namespace" . }}
spec:
  allocationRef: # Elastic IP Address
    from:
      name: {{ include "ack-factory.name" . }}
  subnetRef:
    from:
      name: {{ include "ack-factory.name" . }}-{{ .Values.ack.gateway.subnet }}
  connectivityType: "public"
  tags:
  {{- toYaml .Values.ack.tags | nindent 4 }}
---
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: RouteTable
metadata:
  {{- with .Values.additionalAnnotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    {{- include "ack-factory.labels" . | nindent 4 }}
  name: {{ include "ack-factory.name" . }}
  namespace: {{ template "ack-factory.namespace" . }}
spec:
  routes:
    - destinationCIDRBlock: {{ .Values.ack.gateway.routes.gateway }}
      gatewayRef:
        from:
          name: {{ include "ack-factory.name" . }}
    - destinationCIDRBlock: {{ .Values.ack.gateway.routes.natGateway }}
      natGatewayRef:
        from:
          name: {{ include "ack-factory.name" . }}
  vpcRef:
    from:
      name: {{ include "ack-factory.name" . }}
  tags:
  {{- toYaml .Values.ack.tags | nindent 4 }}